version: "3.8"
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "fanatics", "-p", "fanatics" ]
      interval: 10s
      timeout: 5s
      retries: 10
  mysql:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: exercisegenerator
      MYSQL_USER: fanatics
      MYSQL_PASSWORD: fanatics
      MYSQL_ROOT_PASSWORD: fanatics
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
