name: CI workflow
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build_and_compile_core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Validate the compilation process
        run: mvn -B compile --file ./OcrExerciseGenerator-core/pom.xml
  build_and_compile_app:
    needs: build_and_compile_core
    runs-on: ubuntu-latest
    container:
      image: docker:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Validate the compilation process
        run: docker-compose up
  unit_tests:
    needs: build_and_compile_web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run unit tests
        run: mvn install --file ./OcrExerciseGenerator-core/pom.xml
             mvn -B test --file ./OcrExerciseGenerator-web/pom.xml
  integration_tests:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run integration tests
        run: mvn install --file ./OcrExerciseGenerator-core/pom.xml
             mvn -B verify --file ./OcrExerciseGenerator-web/pom.xml